### ISSUE TITLE
nginx-pdf wird beim workspace restart doppelt erzeugt

### ISSUE THREAD

**Issue by jemand771** [ba-latex/Vorlage-Latex#104]
```
docker: Error response from daemon: Conflict. The container name "/ngix-pdf" is already in use by container "b0263c703156851f17355aaa2a0fe3ec9adb4de3c9aad216e437e0ec202e3121". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
ursache: wenn man einen gitpod workspace stoppt und neu startet, werden die commands neu ausgefüht. ich dachte eigentlich, der nginx-container wird beim stop gekillt, wurde er aber scheinbar nicht

kann auch gut sein, dass das erst nach ner halben minute oder so passiert (und ein workspace restart später das problem gar nicht hat)

so oder so beobachte ich das erstmal. konkret gibt's da nicht wirklich druck, weil der alte container ja immernoch läuft. (im zweifelsfall durch `-restart=always` wiederbelebt wird)

**Comment by DSczyrba** [comment]
Ist das von Seitens Gitpod so gedacht?

**Comment by jemand771** [comment]
nicht sicher, ich beobachte das und kümmer mich evtl. drum ^^
