### ISSUE TITLE
Umzug in Organisation; Releases / Tags vereinheitlichen

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#141]
Vorlage-Latex in @ba-latex umziehen (ich bin immernoch für BA-TeX...), dort Vorlage-Light Vorlage-Latex extrahieren

Releases / Tags in ein einheitliches Format bringen.
Releases #.#.# ; Tags v#.#.#

**Comment by DSczyrba** [comment]
kann das jetzt mal werden?

**Comment by TheColin21** [comment]
ich denke schon. ich weiß nicht, ob wir uns noch vorher um #155 kümmern wollen. müssen wir aber auch nicht. Allgemein find ich es nicht schlimm, falls wir das nicht für v3.0 hinkriegen. Ist ja nicht breaking.

**Comment by TheColin21** [comment]
wäre an dem Punkt aber eher ein @jemand771 -Problem

**Comment by TheColin21** [comment]
Tags von @jemand771 korrigiert, Releases von mir
