### ISSUE TITLE
Datumsformat evtl. anpassen?!

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#160]
![image](https://user-images.githubusercontent.com/45792945/161402111-29844bef-edae-439a-8279-12aac8e795bb.png)

Sollte das nicht von der Optik her eher der 01.12. sein?

**Comment by TheColin21** [comment]
Samma hast du um die Zeit nichts besseres zu tun?😂 Aber ja, würde nicht schaden😅

**Comment by DSczyrba** [comment]
Colins Ding eigentlich

**Comment by TheColin21** [comment]
ich scheitere xD es weigert sich

**Comment by DSczyrba** [comment]
wird gefixt durch: https://github.com/ba-latex/Vorlage-Latex/pull/170
