### ISSUE TITLE
Der Abstand ist zu groß

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#161]
![image](https://user-images.githubusercontent.com/45792945/161402321-a8840a0d-9f44-4a2e-b2cd-5a42cd01ca0e.png)

Kümmer ich mich

**Comment by TheColin21** [comment]
Jung des is keine 4.0.0. das is vielleicht ne 3.0.1, zusammen mit #160 
Aber gut, dass du dich kümmerst😅

**Comment by jemand771** [comment]
haben wir den nicht... mit absicht grösser gemacht?

**Comment by DSczyrba** [comment]
Glaube nicht, aber der ist halt wirklich gigantisch, wir sollten mal in der HAWA schauen, ob die auch so einen massiven Abstand machen.

**Comment by DSczyrba** [comment]
![image](https://user-images.githubusercontent.com/45792945/175925027-1757c655-a499-46e8-87cb-3fd57c74d479.png)

So sieht das ganze laut HAWA aus, hat sich also in meinen Augen erledigt...
