### ISSUE TITLE
Sperrvermerk hinzufügen

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#164]
Laut HAWA muss ein Sperrvermerk (wenn gewünscht) zwischen Deckblatt und Themenblatt eingefügt werden.

Ich werde einen optionalen Sperrvermerk (per metadaten schaltbar) einbauen.
Text:
"Die vorgelegte Bachelorarbeit basiert auf internen, vertraulichen Daten und Informationen des Unternehmens XY. In diese Arbeit dürfen Dritte, mit Ausnahme der Gutachter und befugten Mitgliedern des Prüfungsausschusses, ohne ausdrückliche Zustimmung des Unternehmens und des Verfassers keine Einsicht nehmen. Eine Vervielfältigung und Veröffentlichung der Bachelorarbeit ohne ausdrückliche Genehmigung – auch auszugsweise – ist nicht erlaubt."

**Comment by TheColin21** [comment]
ich merk grade, dass ich ja schonmal ne Freigabeerklärung gebaut habe. Das heißt, es gibt wohl entweder eine Freigabeerklärung im Anhang oder einen Sperrvermerk am Anfang? Ich werd das umschaltbar machen

**Comment by TheColin21** [comment]
Noch anders: Wenn ich das richtig verstehe, kann man, optional, die Bachelor-Arbeit zur öffentlichen Einsicht freigeben. Die Freigabeerklärung ist also immer relevant. Der Sperrvermerk verbietet jegliche Einscht durch alle, außer den genannten.

_oder_ ?

**Comment by DSczyrba** [comment]
Ich glaube der muss immer rein. Die Frage ist nur wie.
Aber wir werden die kaum alle veröffentlichen dürfen 🙈

**Comment by TheColin21** [comment]
Wer muss immer rein?

**Comment by DSczyrba** [comment]
Keine Ahnung. Ich muss Mal genau lesen....
