### ISSUE TITLE
Formelumgebung ist nicht wie in der HAWA

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#173]
Soll:

![image](https://user-images.githubusercontent.com/45792945/176857119-96063431-6845-48a6-9cb7-8386a3503cf6.png)

So sieht es aber aus:

![image](https://user-images.githubusercontent.com/45792945/176857191-8917044c-46ea-4cba-800a-df457382e297.png)

Bzw. so:

![image](https://user-images.githubusercontent.com/45792945/176857232-32539976-1e61-4082-b5a4-e937bc983162.png)

**Comment by TheColin21** [comment]
hatten wir das nicht mal korrekt? hätte uns das nich viel eher auffallen müssen?

**Comment by DSczyrba** [comment]
Ich meine die Platzierung der Caption, die müsste Rechts sein, und nicht wie bei uns obendrüber oder untendrunter....

Weiß nicht, warum uns das bis jetzt nicht aufgefallen ist, wir scheinen keine Formel in der Doku-Text.tex zu haben

**Comment by TheColin21** [comment]
haben wir tatsächlich nicht

**Comment by DSczyrba** [comment]
Scheiße....

**Comment by TheColin21** [comment]
warum zum teufel verweisen wir in hinweise.md auf captionabove? warum will man eine caption above?

**Comment by jemand771** [comment]
aaaah lol, hab gar nicht gesehen dass die rechts stehen muss. ich dachte dir geht's um oben/unten, whoops

**Comment by DSczyrba** [comment]
Ja, weil mit CaptionAbove, das glauche ich so gedacht war, das es mal Rechtsbündig wird...
Wie haben wir denn das übersehen...?

**Comment by TheColin21** [comment]
das sollte eine captionbeside umgebung nutzen

**Comment by jemand771** [comment]
> Wie haben wir denn das übersehen...?

kein mensch benutzt formeln  ¯\_(ツ)_/¯

**Comment by TheColin21** [comment]
s. https://tex.stackexchange.com/questions/649534/captionbeside-flushright
