### ISSUE TITLE
Lösung für fehlende Pakete

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#174]
Wir müssten und mal auf eine Lösung bzw. einen Workflow einigen

**Comment by jemand771** [comment]
aktuell: auf https://github.com/jemand771/latex-build/issues/new gehen und lieb fragen
ja, das sollte besser gehen

("gibt es denn keine bessere lösung?")

**Comment by jemand771** [comment]
ich seh hier spontan mehrere ansätze (wie schon kurz besprochen):
1. debian-pakete via apt
+die gesamte texlive install ist schon apt
+ziemlich einfach
-unsicher, wie wir pakete persistieren können
-zuordnung latex-paketname <-> debian-paket nicht immer eindeutig
-nicht alle latex-pakete sind als deb verfügbar
2. tlmgr im container aufsetzen
+ctan -> alle pakete klar benannt und verfügbar
+von texlive aus "gedachte" lösung
-initiales setup tlmgr (hatte das glaube schonmal probiert, hat mich angeschrien)
-wo/wie persistieren wir pakete
3. manuell ordner reinreichen
+transparent
+schnell
-.sty selber bereitstellen
-keine updates

ausserdem seh ich verschiedene arten, gewünschte pakete zu konfigurieren:
* docker image-erweiterung (latex-build als base) und im dockerfile pakete installieren
  * ziemlich viel aufwand für wenig nutzen, aber theoretisch die sauberste lösung
* umgebungsvariable mit paketnamen
  * persistenz wichtig, und build mit install dauert länger (nicht mehr offline!)
* mount: einfach hinlegen (duh)

**Comment by TheColin21** [comment]
ich denke tatsächlich grade, dass 3. wahrscheinlich am einfachsten ist. und es folgt dem schema, dass eine containerversion nur eine paketversion mit hat... wenn man das auf paketversion x.y baut und drei jahre später das projekt nochmal bauen möchte, wird paketversion x.y noch funktionieren. die aktuelle vielleicht nicht

**Comment by jemand771** [comment]
weil wir braindead sind ist keinem aufgefallen dass man einfach `meinlieblingspaket.sty` in den dokument-ordner hauen und per `\usepackage{meinlieblingspaket}` laden kann. geht auch mit unterordnern, nur die dateierweiterung darf nicht mit ran

automatische on the fly installs a la miktex wären zwar geil, seh ich aber nicht als so dringend für die vorlage an :D
