### ISSUE TITLE
vglinks, zitate etc. funktionieren nicht bei Abbildungsunterschriften

### ISSUE THREAD

**Issue by rearatrox** [ba-latex/Vorlage-Latex#179]
Wie der Titel schon vermuten lässt, funktionieren vglinks und zitate bei den Benennungen der Abbilungen nicht, es kommt folgender Build-Fehler:

![image](https://user-images.githubusercontent.com/68115546/177509982-4b081a32-78eb-4c96-b36b-eb97ae5a416c.png)

... bei folgendem Beispiel: 

![image](https://user-images.githubusercontent.com/68115546/177510110-6aed7f63-aec8-49a6-8769-1f76de888443.png)

Das wars auch schon.

**Comment by TheColin21** [comment]
ich bin ja der meinung wir sollten das vglink command gleich löschen xD

**Comment by DSczyrba** [comment]
Warum?
Da müsste man die ganze Zeile manuell tippen, mit Link und Datum?
Was macht das für einen Sinn?

Außerdem löst es das Problem nicht

**Comment by DSczyrba** [comment]
@rearatrox 

![image](https://user-images.githubusercontent.com/45792945/177519124-77e7e769-b27f-45b8-bc6c-47cdf43e70cb.png)

So wäre doch dann richtig oder?

**Comment by TheColin21** [comment]
jaa is ja richtig... ich hab das nur noch nie genutzt xD müssen halt für caption für TOF und anzuzeigende caption n weiteres argument an sämtliche umgebungscommands anfügen und ich weiß ausm kopf nich wie man das mit optionalem argument macht

**Comment by TheColin21** [comment]
man könnte es auch anders hacky machen. immer ein argument mehr verlangen, mit ifthen unterscheiden, ob das zusatz caption feld leer is und dementsprechend umschalten. aber das wär n breaking change und es mir nich wert
