### ISSUE TITLE
Falsche Nummerierung in Verzeichnissen

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#183]
![image](https://user-images.githubusercontent.com/45792945/177546941-862d8203-3999-453f-8be8-d578ba962eed.png)

Abbildung 1, nicht 2.1

**Comment by TheColin21** [comment]
fixed by https://github.com/ba-latex/Vorlage-Latex/commit/e4fb5a20b042b3a4ad0321348f55d6f58ab3ffc0
