### ISSUE TITLE
\mdseries im Verzeichnis

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#184]
![image](https://user-images.githubusercontent.com/45792945/177547187-3fe9d29c-3f5f-4f81-9eb0-a93cf8ed2670.png)

**Comment by TheColin21** [comment]
ich musste `\addtokomafont{sectionentry}{\mdseries}` auskommentieren. damit hat das dokument nicht gebaut. klingt hiernach

**Comment by TheColin21** [comment]
fixed by https://github.com/ba-latex/Vorlage-Latex/commit/3833337ece2b842616e9e0e4d3bf327469da3838
