### ISSUE TITLE
Anhangverzeichnis

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#187]
![image](https://user-images.githubusercontent.com/45792945/177547758-57553f7d-7f89-41c0-9184-a7763bbd5781.png)

**Comment by TheColin21** [comment]
fixed by https://github.com/ba-latex/Vorlage-Latex/commit/8c04aff9ebde1dbe24359dc8d19e9369dd125db9 and https://github.com/ba-latex/Vorlage-Latex/commit/c7d3b49aa7546bfe54df91f7d7b1ed4aca4de511
