### ISSUE TITLE
Inhaltsverzeichnis

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#189]
![image](https://user-images.githubusercontent.com/45792945/177550558-ea628158-af13-4b63-833e-d718a46a8b17.png)

Irgendwas ist hier auch derbst im Argen...

**Comment by DSczyrba** [comment]
Fixe ich.

**Comment by TheColin21** [comment]
nö, fixe ich xD in https://github.com/ba-latex/Vorlage-Latex/commit/31582d80fd614e5e760069c96b08182f244fdc89
