### ISSUE TITLE
Erklärungen sollten nicht im Anhangsverzeichnis auftauchen

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#205]
laut HAWA 3.3.2.1 ist die Ehrenwörtliche Erklärung ein Bestandteil der Arbeiten nach Anhangsverzeichnis und Anhängen. Die sollte also nicht im Anhangsverzeichnis auftauchen. Ich interpretiere das mal so, dass das auch für die Zustimmung zur Plagiatsprüfung gilt.

Lösung wahrscheinlich: `\chapter{XXX}` durch `\lohead{\textnormal{XXX}}` ersetzen.

Sollten wir noch vorsichtshalber auf Seiteneffekte prüfen

**Comment by TheColin21** [comment]
achja und `rohead` muss geleert werden...

**Comment by DSczyrba** [comment]
Ich glaube, wenn man statt \chapter{} einfach \addchap{} macht, dann sollte das nicht im Verzeichnis landen, kann das mal einer fix testen?

**Comment by TheColin21** [comment]
Kann sein😅 teste ich vor abgabe eh nich mehr

Am 29. Juli 2022 13:09:18 MESZ schrieb DSczyrba ***@***.***>:

**Comment by TheColin21** [comment]
scheint nicht zu funktionieren, mglw. wegen der neudefinition von \chapter
