### ISSUE TITLE
Änderungen nach BT Erfahrungen

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#206]
Ich hab während meiner Bachelorthesis festgestellt, dass es wahrscheinlich eine bessere Idee wäre, floats nicht mit [H] von vornherein an eine Position zu zwingen. Das sollte der letzte Ausweg sein, falls es sonst scheiße aussieht. Nicht der Standard. 
Vorschlag: 
- Commands `\bild`, `\svg`, `\formula` von [H] auf [h] umstellen (edit: verzeichnis würde ich lassen, weil wahrscheinlich häufig zu groß)

Außerdem sind Codes imho mit standard schriftgröße deutlich zu groß. Ich hab sie bis jetzt in all meinen arbeiten auf Scriptsize.
Vorschlag (da scriptsize wirklich ziemlich klein ist):
- `fontsize=\footnotesize` in `\setminted`

Was sagt ihr dazu? habt ihr noch andere solche dinge? findet ihr das scheiße und würdets eher so lassen? 😅

**Comment by TheColin21** [comment]
ich hab das mal testweise so in dev-bt-fixes umgesetzt...

**Comment by jemand771** [comment]
hmm, ich glaub zur minted-schriftgrösse hatten wir schonmal diskutiert, das kommt immer etwas auf die art des codes an.
wenn man nur so 5-6 zeilen zeigt ist so wie jetzt besser, wenn du aber deine 40 zeilen config in den fliesstext packen willst (oder deinen gesamten praxisteil in den anhang) macht sich footnotesize besser

**Comment by TheColin21** [comment]
naja ich hatte auch bei kleineren Schnipseln probleme bei langen zeilen... wie gesagt is das halt dauernd umgebrochen... is ja aber auch nur n standardwert

**Comment by jemand771** [comment]
schreib halt keine langen zeilen 😎 
ist witzig, weil gängige python-linter dich by default anschreien, wenn eine zeile >79 (oder >120) zeichen ist

**Comment by TheColin21** [comment]
ich würde es auf footnotesize setzen 😅  andere meinungen? dann müsste ich die #207 nochmal anpassen
