### ISSUE TITLE
Institutionsnamen in Bibliographie in CAPS

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#208]
laut HAWA Layoutvorgaben sind Institutionsnamen _überall_ in CAPS zu schreiben. Im Fließtext würde ich das lassen weil hässlich und wahlweise dem Autor überlassen. In Fußnoten und Quellenverzeichnis sollten wir das umsetzen. 

Jemand auf anhieb ideen wie? 😅

**Comment by jemand771** [comment]
meh, ich find `author = {{INTENTA GmbH}}` fine. wüsste nicht, wie wir das (automatisch) von `author = {{xXanonForumUserXx}}` unterscheiden sollen

**Comment by TheColin21** [comment]
auch wahr. in dem fall würde ich das einfach als standard rein schreiben und nen kleinen hinweis ins bibfile schmeißen
