### ISSUE TITLE
Entspanntere Positionierung von Floatumgebungen im Dev Branch (commit: 7fe66d970a8dc9fcb455b94e0d42c027486ad70f)

### ISSUE THREAD

**Issue by ParkerSnable** [ba-latex/Vorlage-Latex#211]
Bzgl. den Änderungen wie ```\begin{code}[H] -> \begin{code}[h]``` als Standard für Positionierungen von Floatumgebungen verschlechtert (zumindest bei meiner BA) in den meisten Fällen die Positionierung und ist evtl. auch nicht das was ein neuer Nutzer erwarten würde.

Eine Idee wäre entweder bei 'H' zu bleiben, oder aber zumindest 'htb' zu testen, ggf. sogar '!htb', was allerdings nicht häufig, bzw. als Standardeinstellung dienen sollte. 

Vielleicht könnte das noch jemand ausprobieren und seine Meinung dazu abgeben.

Hier noch ein paar Kommentare zur Funktionsweise:
https://tex.stackexchange.com/questions/8652/what-does-t-and-ht-mean/8653#8653

VA. @TheColin21

**Comment by TheColin21** [comment]
ich teste gleichmal. ich würde wahrscheinlich die reihenfolge `hptb` setzen

**Comment by DSczyrba** [comment]
Wir hatten das Thema gestern schon im RocketChat, und ich hatte damals mich auch für das `H` entschieden, denn das ist die Platzierung, die der gediegene MS-Word-Nutzer erwartet.
In meinen Augen ist es besser, bei dem `H` zu bleiben und der fortgeschrittenere Nutzer könnte das ja für sich individuell anpassen.
Ein `h` zu benutzen oder eins der anderen erfordert in meinen Augen zu viel Grundlagenwissen und die Vorlage baut ja gerade darauf auf, dass dieses nicht benötigt wird.

**Comment by TheColin21** [comment]
Ich find halt, dass ein H ein zu starkes "downgrade" der intelligenz ist, die LaTeX mitbringt. Wer Word-Verhalten will, kann Word nutzen. Trotzdem ist hptb näher dran als h, einfach weil es die gleiche Seite stärker priorisiert. Deshalb finde ich den Mittelweg gut

**Comment by TheColin21** [comment]
Alternative: wir definieren eine stelle, wo ein default steht. Kriegen wir LaTeX irgendwie dazu, das als ne art variable zu sehen? Dass wir da quasi überall X reinschreiben und der löst auf?

**Comment by DSczyrba** [comment]
Ich finde es auch ziemlich riskant hier jetzt als release so ne geforcte Änderung zu bringen.
Wenn man schon recht weit ist, muss man jetzt alles nochmal anfassen...

**Comment by DSczyrba** [comment]
> Alternative: wir definieren eine stelle, wo ein default steht. Kriegen wir LaTeX irgendwie dazu, das als ne art variable zu sehen? Dass wir da quasi überall X reinschreiben und der löst auf?

Glaube ich kaum, das wird so nicht funktionieren... Man könnte es bestimmt weglassen, komplett und dann den Default-Wert neu deklarieren.

**Comment by TheColin21** [comment]
Das is ja nich erzwungen. Ich finde die Änderung an sich sehr sinnvoll. Was sagt @jemand771 dazu? 
Wenn natürlich alle für ein `H` sind, ist das so😅 
Falls du das nur nichmehr jetzt haben willst, könnte man da auch ne vorlage 4.3 machen. Oder ne 5, wenn du meinst, das wär breaking😅

**Comment by TheColin21** [comment]
nach etwas recherche habe ich keine möglichkeit gefunden, einen globalen standardwert für die float positionierung zu setzen. Soll ich in dem Fall die Änderungen daran rückgängig machen, und zurück auf `H` gehen?

**Comment by TheColin21** [comment]
für Version 4.2.0 habe ich die Positionierung auf H zurück gesetzt. Für eine zukünftige Version würde ich trotzdem gern auf `hptb` gehen.

**Comment by jemand771** [comment]
Ich denke, hier sollten wir einfach wenn wir zeit haben nochmal bisschen rumprobieren - also, vorherige arbeiten mal mit H und mal mit hptb bauen, und gucken wie es sich anstellt.
Ich hatte in der bachelorthesis auch das gefühl, dass LaTeX suboptimale entscheidungen getroffen hat (bzw. dass ich die bild commands an stellen gepackt hab, die LaTeX dazu gebracht haben rotz zu machen)

**Comment by TheColin21** [comment]
die Arbeiten sind abgegeben. wollen wir uns das nochmal anschauen? Ich bin für `hptb`. könnten wir an unseren arbeiten mal durchtesten

**Comment by TheColin21** [comment]
@DSczyrba hat in seiner BT damit experimentiert und is dabei interessanterweise darauf gekommen, dass für ihn `ptbh` [?] besser zu funktionieren schien als `hptb`. Kann ich nicht nachvollziehen, müssen wir testen

**Comment by TheColin21** [comment]
Ich habe das ganze bei meiner Bachelorthesis getestet. `hptb` und `ptbh` haben sich bei mir exakt gleich verhalten. höchstwahrscheinlich, weil das `h` von bei mir eh nie genutzt wurde, das `ptb` aber immer zu einer zufriedenstellenden Positionierung geführt hat. ich bin trotzdem dafür, eine Positionierung _hier_ einer irgendwo sonst vorzuziehen wenn möglich. 
ich bin also weiter für `hptb`

Interessant beim Vergleich zu `H` ist auch interessant, dass sich die Formatierung des Float-Inhalts ändert.
Links mit `hptb`, rechts mit `H`
![grafik](https://user-images.githubusercontent.com/24256864/191734646-a0efe5e9-6879-44ad-a719-815d3011a4cd.png)

![grafik](https://user-images.githubusercontent.com/24256864/191735020-8d0a59c7-5e84-4537-abcb-d07eda56be52.png)

ansonsten hat `H` teilweise deutlich unschönere Seiten verursacht als `hptb`, durch die verschiedenen Größen is das aber teils auch schwer vergleichbar.

**Comment by jemand771** [comment]
die tabelle links sieht sooo scheiße aus. wenn wir den text mit was anderem als `H` entquetscht bekommen können wir nochmal drüber reden, aber so gefällt mir überhaupt nicht

war auch der hauptgrund, warum ich überall `H` verwendet + das issue nicht weiter beachtet hab - tabellen werden damit einfach komisch, und ich weiß noch nicht, wieso

**Comment by TheColin21** [comment]
Die optik der tabellen is wieder geschmackssache.. ich persönlich mag das links fast mehr... verstehs aber auch andersrum...

Ich wüsste wirklich gern, wieso das passiert...hab gesucht, konnte nichts finden...

Bock kurz zu googlen bevor ich wieder dumm in nem forum frag?😅

Aber ja sind ja nich nur Tabellen...

**Comment by TheColin21** [comment]
es gibt news. ich wollte in nem Forum fragen und dafür ein MWE bauen und dabei habe ich rausgefunden, worans grob liegt:
setspace in verbindung mit höherem linespread.

```

%! LaTeX Vorlage
\documentclass{scrreprt}

\usepackage{setspace}
\usepackage{float}
\usepackage{minted}

\DeclareNewTOC[
  type=code,                           % Name der Umgebung
  types=codes,                         % Erweiterung (\listofschemes)
  float,                               % soll gleiten
]{loc}
\setuptoc{loc}{totoc}

\linespread{2}

\begin{document}
\chapter{Code-Examples}
\section{Code-Example with H}
\begin{code}[H]
  \begin{minted}{python}
      class Wooo(Foo):
          def __init__(self, boo):
              self.doo = boo
              moo = 1 + 2 +3
  \end{minted}
  \caption{Beispielcode}
\end{code}
\section{Code-Example with hptb}
\begin{code}[hptb]
  \begin{minted}{python}
      class Wooo(Foo):
          def __init__(self, boo):
              self.doo = boo
              moo = 1 + 2 +3
  \end{minted}
  \caption{Beispielcode}
\end{code}
\end{document}
```
![image](https://user-images.githubusercontent.com/24256864/194526228-5eaf1ca8-36da-48aa-9613-7b22a40bc418.png)

**Comment by TheColin21** [comment]
https://tex.stackexchange.com/questions/660823/differences-in-float-content-linespread-with-different-positioning-parameters-wh ich hab das mal angefragt....

**Comment by TheColin21** [comment]
ich muss zugeben, @DSczyrba  hatte recht (ich glaube in dem geschlossenen PR): `p` sorgt nicht für die gleiche Seite, sondern für eine "page of floats". `p` würde ich also tatsächlich als letzten Ausweg sehen. neue Prio: `htbp`, PR incoming, inklusive einheitlichem Spacing

**Comment by TheColin21** [comment]
resolved by #217
