### ISSUE TITLE
Node 12 Actions sind deprecated

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#225]
![image](https://user-images.githubusercontent.com/45792945/212878933-a450623b-2758-4080-80a9-d7d200e8802b.png)

**Comment by TheColin21** [comment]
Klingt nach Willy

**Comment by jemand771** [comment]
­>
![image](https://user-images.githubusercontent.com/19669567/212879539-229506df-9242-4a5c-b46b-65d5edd37c1e.png)

**Comment by jemand771** [comment]
[actions/checkout](https://github.com/actions/checkout)
[actions/upload-artifact](https://github.com/actions/upload-artifact)
[actions/download-artifact](https://github.com/actions/download-artifact)
stehen bei uns in [document-build.yml](https://github.com/ba-latex/Vorlage-Latex/blob/master/.github/workflows/document-build.yml) alle auf `v2`, das sollte man bei allen ohne probleme auf `v3` ziehen können
