### ISSUE TITLE
xcolor Paket stört spacing

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#229]
![grafik](https://user-images.githubusercontent.com/24256864/226615836-490e5fe1-312a-4c7f-a2f4-da167d7fec2c.png)

**Comment by jemand771** [comment]
wenn du cool bist einfach 9dc316d2554e6629ce3e5daa3d6e2f0ba5c194dd oder die ganze PR reverten

psst, wer die scheiße approved hat will ich wissen https://github.com/ba-latex/Vorlage-Latex/pull/222
