### ISSUE TITLE
Nummerierung Anhang

### ISSUE THREAD

**Issue by DSczyrba** [ba-latex/Vorlage-Latex#44]
einzelne Anhänge mit mehreren Seiten werden in sich arabisch num-meriert

**Comment by DSczyrba** [comment]
Wird sich mit nennenswerten Aufwand nicht automatisieren lassen...
Falls Anhänge mehrere Seiten haben, würde ich vorschlagen manuell zu numerieren...

Eben von `\pagenumbering{gobble}` auf `\pagenumbering{arabic}` stellen und davor `\setcounter{page}{1}` den Counter mit der Hand auf 1 setzen...

Bei Gelegenheit könnte man das ja mal beispielhaft einbauen und dann auch den Issue hier schließen...

@jemand771 @TheColin21  :D

**Comment by TheColin21** [comment]
Ich halte das für nen Fall für dev-beleg und würde das da mit einbauen.

**Comment by DSczyrba** [comment]
Ja da hast du Recht. Machen wir so.
