### ISSUE TITLE
vorlage.tex und vorlage_light.tex kombinieren o.Ä.

### ISSUE THREAD

**Issue by TheColin21** [ba-latex/Vorlage-Latex#57]
Aktuell sind die volle vorlage.tex und die light-Version fast identisch. Einige Zeilen sind auskommentiert, manche entfernt, manche kommen dazu, aber geschätzt 90% des Codes sind gleich. Die Light-Version neben der Hauptversion zu pflegen ist unnötiger aufwand. Aktuell wird in der Light-Version bei Minted z.B. auf latex.out verwiesen und ich habe meine "Diversen Detailverbesserungen" aus #56 nur in der Hauptversion angepasst.

Mögliche Ansätze: 
- Eine Art Switch-Variable, mit der man zwischen Light und Full umschalten kann (<-- mein Favorit, einfach per if else)
  - [https://www.matthiaspospiech.de/blog/2008/04/13/latex-variablen-if-abfragen-und-schleifen/](https://www.matthiaspospiech.de/blog/2008/04/13/latex-variablen-if-abfragen-und-schleifen/)
- Eine gemeinsame Include-Datei, die den gemeinsamen Code beinhaltet und zwei kleinere Dateien für den Rest
- Light-Version als Fork dieses Repos
- weitere...?

**Comment by jemand771** [comment]
lacht in https://github.com/DSczyrba/Vorlage-Latex/issues/51#issuecomment-765489272

fork ist blöd. entweder so hier: https://github.com/DSczyrba/Vorlage-Latex/issues/51#issuecomment-836345434 oder mit if/else. letzteres könnte allerdings ganz schön lang werden

**Comment by TheColin21** [comment]
ja, ich wollte eigentlich nur die assignen xD

**Comment by DSczyrba** [comment]
Generell sollte die Vorlage ja auf lange Sicht auch mal eine *.cls Datei werden.
Die Lightversion, ist halt getrennt zu betrachten, die braucht halt nicht die Kapite.tex und das ganze Ordner Klimbimm...

Außerdem ging ich long term von aus, dass die beiden sich unterscheiden werden.

**Comment by DSczyrba** [comment]
Wir lassen das erstmal, ist momentan nicht wichtig.

**Comment by TheColin21** [comment]
Ich hab das mal wieder geöffnet. Wollen wir das jetzt in der Organisation machen und wenn ja, wie?
